---
type: docker
kind: pipeline
name: default

steps:
  - name: build
    image: node
    commands:
      - npm install
      - npm run build
  - name: docker
    image: plugins/docker
    settings:
      username: 1995parham
      password:
        from_secret: docker_password
      repo: 1995parham/aut-tv
      tags: latest
